#:schema node_modules/wrangler/config-schema.json

name = "endpoint"
main = "worker.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
ENDPOINT_TUNNEL_SECRET="tunnel_secret_here"

[[kv_namespaces]]
binding = "KV"
id = "kv_id_here"
