#:schema node_modules/wrangler/config-schema.json

name = "endpoint"
main = "worker.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "fd8b52e576d444ac95bbfa55f6ec2d50"
